import React, {StyleSheet, Dimensions, PixelRatio} from "react-native";
const {width, height, scale} = Dimensions.get("window"),
    vw = width / 100,
    vh = height / 100,
    vmin = Math.min(vw, vh),
    vmax = Math.max(vw, vh);

export default StyleSheet.create({
    "html": {
        "marginTop": 0,
        "marginRight": 0,
        "marginBottom": 0,
        "marginLeft": 0,
        "paddingTop": 0,
        "paddingRight": 0,
        "paddingBottom": 0,
        "paddingLeft": 0,
        "border": 0,
        "fontSize": "100%",
        "font": "inherit",
        "verticalAlign": "baseline"
    },
    "body": {
        "marginTop": 0,
        "marginRight": 0,
        "marginBottom": 0,
        "marginLeft": 0,
        "paddingTop": 0,
        "paddingRight": 0,
        "paddingBottom": 0,
        "paddingLeft": 0,
        "border": 0,
        "fontSize": "100%",
        "font": "inherit",
        "verticalAlign": "baseline",
        "lineHeight": 1,
        "fontFamily": "'PT Sans', sans-serif",
        "minHeight": 740,
        "background": "radial-gradient(rgb(240, 240, 240), rgb(190, 190, 190))"
    },
    "div": {
        "marginTop": 0,
        "marginRight": 0,
        "marginBottom": 0,
        "marginLeft": 0,
        "paddingTop": 0,
        "paddingRight": 0,
        "paddingBottom": 0,
        "paddingLeft": 0,
        "border": 0,
        "fontSize": "100%",
        "font": "inherit",
        "verticalAlign": "baseline"
    },
    "span": {
        "marginTop": 0,
        "marginRight": 0,
        "marginBottom": 0,
        "marginLeft": 0,
        "paddingTop": 0,
        "paddingRight": 0,
        "paddingBottom": 0,
        "paddingLeft": 0,
        "border": 0,
        "fontSize": "100%",
        "font": "inherit",
        "verticalAlign": "baseline"
    },
    "applet": {
        "marginTop": 0,
        "marginRight": 0,
        "marginBottom": 0,
        "marginLeft": 0,
        "paddingTop": 0,
        "paddingRight": 0,
        "paddingBottom": 0,
        "paddingLeft": 0,
        "border": 0,
        "fontSize": "100%",
        "font": "inherit",
        "verticalAlign": "baseline"
    },
    "object": {
        "marginTop": 0,
        "marginRight": 0,
        "marginBottom": 0,
        "marginLeft": 0,
        "paddingTop": 0,
        "paddingRight": 0,
        "paddingBottom": 0,
        "paddingLeft": 0,
        "border": 0,
        "fontSize": "100%",
        "font": "inherit",
        "verticalAlign": "baseline"
    },
    "iframe": {
        "marginTop": 0,
        "marginRight": 0,
        "marginBottom": 0,
        "marginLeft": 0,
        "paddingTop": 0,
        "paddingRight": 0,
        "paddingBottom": 0,
        "paddingLeft": 0,
        "border": 0,
        "fontSize": "100%",
        "font": "inherit",
        "verticalAlign": "baseline"
    },
    "h1": {
        "marginTop": 0,
        "marginRight": 0,
        "marginBottom": 0,
        "marginLeft": 0,
        "paddingTop": 0,
        "paddingRight": 0,
        "paddingBottom": 0,
        "paddingLeft": 0,
        "border": 0,
        "fontSize": "100%",
        "font": "inherit",
        "verticalAlign": "baseline"
    },
    "h2": {
        "marginTop": 0,
        "marginRight": 0,
        "marginBottom": 0,
        "marginLeft": 0,
        "paddingTop": 0,
        "paddingRight": 0,
        "paddingBottom": 0,
        "paddingLeft": 0,
        "border": 0,
        "fontSize": "100%",
        "font": "inherit",
        "verticalAlign": "baseline"
    },
    "h3": {
        "marginTop": 0,
        "marginRight": 0,
        "marginBottom": 0,
        "marginLeft": 0,
        "paddingTop": 0,
        "paddingRight": 0,
        "paddingBottom": 0,
        "paddingLeft": 0,
        "border": 0,
        "fontSize": "100%",
        "font": "inherit",
        "verticalAlign": "baseline"
    },
    "h4": {
        "marginTop": 0,
        "marginRight": 0,
        "marginBottom": 0,
        "marginLeft": 0,
        "paddingTop": 0,
        "paddingRight": 0,
        "paddingBottom": 0,
        "paddingLeft": 0,
        "border": 0,
        "fontSize": "100%",
        "font": "inherit",
        "verticalAlign": "baseline"
    },
    "h5": {
        "marginTop": 0,
        "marginRight": 0,
        "marginBottom": 0,
        "marginLeft": 0,
        "paddingTop": 0,
        "paddingRight": 0,
        "paddingBottom": 0,
        "paddingLeft": 0,
        "border": 0,
        "fontSize": "100%",
        "font": "inherit",
        "verticalAlign": "baseline"
    },
    "h6": {
        "marginTop": 0,
        "marginRight": 0,
        "marginBottom": 0,
        "marginLeft": 0,
        "paddingTop": 0,
        "paddingRight": 0,
        "paddingBottom": 0,
        "paddingLeft": 0,
        "border": 0,
        "fontSize": "100%",
        "font": "inherit",
        "verticalAlign": "baseline"
    },
    "p": {
        "marginTop": 0,
        "marginRight": 0,
        "marginBottom": 0,
        "marginLeft": 0,
        "paddingTop": 0,
        "paddingRight": 0,
        "paddingBottom": 0,
        "paddingLeft": 0,
        "border": 0,
        "fontSize": "100%",
        "font": "inherit",
        "verticalAlign": "baseline"
    },
    "blockquote": {
        "marginTop": 0,
        "marginRight": 0,
        "marginBottom": 0,
        "marginLeft": 0,
        "paddingTop": 0,
        "paddingRight": 0,
        "paddingBottom": 0,
        "paddingLeft": 0,
        "border": 0,
        "fontSize": "100%",
        "font": "inherit",
        "verticalAlign": "baseline",
        "quotes": "none"
    },
    "pre": {
        "marginTop": 0,
        "marginRight": 0,
        "marginBottom": 0,
        "marginLeft": 0,
        "paddingTop": 0,
        "paddingRight": 0,
        "paddingBottom": 0,
        "paddingLeft": 0,
        "border": 0,
        "fontSize": "100%",
        "font": "inherit",
        "verticalAlign": "baseline"
    },
    "a": {
        "marginTop": 0,
        "marginRight": 0,
        "marginBottom": 0,
        "marginLeft": 0,
        "paddingTop": 0,
        "paddingRight": 0.1,
        "paddingBottom": 0,
        "paddingLeft": 0.1,
        "border": 0,
        "fontSize": "100%",
        "font": "inherit",
        "verticalAlign": "baseline",
        "color": "inherit",
        "textDecoration": "none",
        "background": "rgba(255,255,255,0.5)",
        "textShadow": "-1px -1px 2px rgba(100,100,100,0.9)",
        "borderRadius": 0.2,
        "WebkitTransition": "0.5s",
        "MozTransition": "0.5s",
        "MsTransition": "0.5s",
        "OTransition": "0.5s",
        "transition": "0.5s"
    },
    "abbr": {
        "marginTop": 0,
        "marginRight": 0,
        "marginBottom": 0,
        "marginLeft": 0,
        "paddingTop": 0,
        "paddingRight": 0,
        "paddingBottom": 0,
        "paddingLeft": 0,
        "border": 0,
        "fontSize": "100%",
        "font": "inherit",
        "verticalAlign": "baseline"
    },
    "acronym": {
        "marginTop": 0,
        "marginRight": 0,
        "marginBottom": 0,
        "marginLeft": 0,
        "paddingTop": 0,
        "paddingRight": 0,
        "paddingBottom": 0,
        "paddingLeft": 0,
        "border": 0,
        "fontSize": "100%",
        "font": "inherit",
        "verticalAlign": "baseline"
    },
    "address": {
        "marginTop": 0,
        "marginRight": 0,
        "marginBottom": 0,
        "marginLeft": 0,
        "paddingTop": 0,
        "paddingRight": 0,
        "paddingBottom": 0,
        "paddingLeft": 0,
        "border": 0,
        "fontSize": "100%",
        "font": "inherit",
        "verticalAlign": "baseline"
    },
    "big": {
        "marginTop": 0,
        "marginRight": 0,
        "marginBottom": 0,
        "marginLeft": 0,
        "paddingTop": 0,
        "paddingRight": 0,
        "paddingBottom": 0,
        "paddingLeft": 0,
        "border": 0,
        "fontSize": "100%",
        "font": "inherit",
        "verticalAlign": "baseline"
    },
    "cite": {
        "marginTop": 0,
        "marginRight": 0,
        "marginBottom": 0,
        "marginLeft": 0,
        "paddingTop": 0,
        "paddingRight": 0,
        "paddingBottom": 0,
        "paddingLeft": 0,
        "border": 0,
        "fontSize": "100%",
        "font": "inherit",
        "verticalAlign": "baseline"
    },
    "code": {
        "marginTop": 0,
        "marginRight": 0,
        "marginBottom": 0,
        "marginLeft": 0,
        "paddingTop": 0,
        "paddingRight": 0,
        "paddingBottom": 0,
        "paddingLeft": 0,
        "border": 0,
        "fontSize": "100%",
        "font": "inherit",
        "verticalAlign": "baseline"
    },
    "del": {
        "marginTop": 0,
        "marginRight": 0,
        "marginBottom": 0,
        "marginLeft": 0,
        "paddingTop": 0,
        "paddingRight": 0,
        "paddingBottom": 0,
        "paddingLeft": 0,
        "border": 0,
        "fontSize": "100%",
        "font": "inherit",
        "verticalAlign": "baseline"
    },
    "dfn": {
        "marginTop": 0,
        "marginRight": 0,
        "marginBottom": 0,
        "marginLeft": 0,
        "paddingTop": 0,
        "paddingRight": 0,
        "paddingBottom": 0,
        "paddingLeft": 0,
        "border": 0,
        "fontSize": "100%",
        "font": "inherit",
        "verticalAlign": "baseline"
    },
    "em": {
        "marginTop": 0,
        "marginRight": 0,
        "marginBottom": 0,
        "marginLeft": 0,
        "paddingTop": 0,
        "paddingRight": 0,
        "paddingBottom": 0,
        "paddingLeft": 0,
        "border": 0,
        "fontSize": "100%",
        "font": "inherit",
        "verticalAlign": "baseline",
        "fontStyle": "italic"
    },
    "img": {
        "marginTop": 0,
        "marginRight": 0,
        "marginBottom": 0,
        "marginLeft": 0,
        "paddingTop": 0,
        "paddingRight": 0,
        "paddingBottom": 0,
        "paddingLeft": 0,
        "border": 0,
        "fontSize": "100%",
        "font": "inherit",
        "verticalAlign": "baseline"
    },
    "ins": {
        "marginTop": 0,
        "marginRight": 0,
        "marginBottom": 0,
        "marginLeft": 0,
        "paddingTop": 0,
        "paddingRight": 0,
        "paddingBottom": 0,
        "paddingLeft": 0,
        "border": 0,
        "fontSize": "100%",
        "font": "inherit",
        "verticalAlign": "baseline"
    },
    "kbd": {
        "marginTop": 0,
        "marginRight": 0,
        "marginBottom": 0,
        "marginLeft": 0,
        "paddingTop": 0,
        "paddingRight": 0,
        "paddingBottom": 0,
        "paddingLeft": 0,
        "border": 0,
        "fontSize": "100%",
        "font": "inherit",
        "verticalAlign": "baseline"
    },
    "q": {
        "marginTop": 0,
        "marginRight": 0,
        "marginBottom": 0,
        "marginLeft": 0,
        "paddingTop": 0,
        "paddingRight": 0,
        "paddingBottom": 0,
        "paddingLeft": 0,
        "border": 0,
        "fontSize": "100%",
        "font": "inherit",
        "verticalAlign": "baseline",
        "quotes": "none"
    },
    "s": {
        "marginTop": 0,
        "marginRight": 0,
        "marginBottom": 0,
        "marginLeft": 0,
        "paddingTop": 0,
        "paddingRight": 0,
        "paddingBottom": 0,
        "paddingLeft": 0,
        "border": 0,
        "fontSize": "100%",
        "font": "inherit",
        "verticalAlign": "baseline"
    },
    "samp": {
        "marginTop": 0,
        "marginRight": 0,
        "marginBottom": 0,
        "marginLeft": 0,
        "paddingTop": 0,
        "paddingRight": 0,
        "paddingBottom": 0,
        "paddingLeft": 0,
        "border": 0,
        "fontSize": "100%",
        "font": "inherit",
        "verticalAlign": "baseline"
    },
    "small": {
        "marginTop": 0,
        "marginRight": 0,
        "marginBottom": 0,
        "marginLeft": 0,
        "paddingTop": 0,
        "paddingRight": 0,
        "paddingBottom": 0,
        "paddingLeft": 0,
        "border": 0,
        "fontSize": "100%",
        "font": "inherit",
        "verticalAlign": "baseline"
    },
    "strike": {
        "marginTop": 0,
        "marginRight": 0,
        "marginBottom": 0,
        "marginLeft": 0,
        "paddingTop": 0,
        "paddingRight": 0,
        "paddingBottom": 0,
        "paddingLeft": 0,
        "border": 0,
        "fontSize": "100%",
        "font": "inherit",
        "verticalAlign": "baseline"
    },
    "strong": {
        "marginTop": 0,
        "marginRight": 0,
        "marginBottom": 0,
        "marginLeft": 0,
        "paddingTop": 0,
        "paddingRight": 0,
        "paddingBottom": 0,
        "paddingLeft": 0,
        "border": 0,
        "fontSize": "100%",
        "font": "inherit",
        "verticalAlign": "baseline",
        "fontWeight": "bold"
    },
    "sub": {
        "marginTop": 0,
        "marginRight": 0,
        "marginBottom": 0,
        "marginLeft": 0,
        "paddingTop": 0,
        "paddingRight": 0,
        "paddingBottom": 0,
        "paddingLeft": 0,
        "border": 0,
        "fontSize": "100%",
        "font": "inherit",
        "verticalAlign": "baseline"
    },
    "sup": {
        "marginTop": 0,
        "marginRight": 0,
        "marginBottom": 0,
        "marginLeft": 0,
        "paddingTop": 0,
        "paddingRight": 0,
        "paddingBottom": 0,
        "paddingLeft": 0,
        "border": 0,
        "fontSize": "100%",
        "font": "inherit",
        "verticalAlign": "baseline"
    },
    "tt": {
        "marginTop": 0,
        "marginRight": 0,
        "marginBottom": 0,
        "marginLeft": 0,
        "paddingTop": 0,
        "paddingRight": 0,
        "paddingBottom": 0,
        "paddingLeft": 0,
        "border": 0,
        "fontSize": "100%",
        "font": "inherit",
        "verticalAlign": "baseline"
    },
    "var": {
        "marginTop": 0,
        "marginRight": 0,
        "marginBottom": 0,
        "marginLeft": 0,
        "paddingTop": 0,
        "paddingRight": 0,
        "paddingBottom": 0,
        "paddingLeft": 0,
        "border": 0,
        "fontSize": "100%",
        "font": "inherit",
        "verticalAlign": "baseline"
    },
    "b": {
        "marginTop": 0,
        "marginRight": 0,
        "marginBottom": 0,
        "marginLeft": 0,
        "paddingTop": 0,
        "paddingRight": 0,
        "paddingBottom": 0,
        "paddingLeft": 0,
        "border": 0,
        "fontSize": "100%",
        "font": "inherit",
        "verticalAlign": "baseline",
        "fontWeight": "bold"
    },
    "u": {
        "marginTop": 0,
        "marginRight": 0,
        "marginBottom": 0,
        "marginLeft": 0,
        "paddingTop": 0,
        "paddingRight": 0,
        "paddingBottom": 0,
        "paddingLeft": 0,
        "border": 0,
        "fontSize": "100%",
        "font": "inherit",
        "verticalAlign": "baseline"
    },
    "i": {
        "marginTop": 0,
        "marginRight": 0,
        "marginBottom": 0,
        "marginLeft": 0,
        "paddingTop": 0,
        "paddingRight": 0,
        "paddingBottom": 0,
        "paddingLeft": 0,
        "border": 0,
        "fontSize": "100%",
        "font": "inherit",
        "verticalAlign": "baseline",
        "fontStyle": "italic"
    },
    "center": {
        "marginTop": 0,
        "marginRight": 0,
        "marginBottom": 0,
        "marginLeft": 0,
        "paddingTop": 0,
        "paddingRight": 0,
        "paddingBottom": 0,
        "paddingLeft": 0,
        "border": 0,
        "fontSize": "100%",
        "font": "inherit",
        "verticalAlign": "baseline"
    },
    "dl": {
        "marginTop": 0,
        "marginRight": 0,
        "marginBottom": 0,
        "marginLeft": 0,
        "paddingTop": 0,
        "paddingRight": 0,
        "paddingBottom": 0,
        "paddingLeft": 0,
        "border": 0,
        "fontSize": "100%",
        "font": "inherit",
        "verticalAlign": "baseline"
    },
    "dt": {
        "marginTop": 0,
        "marginRight": 0,
        "marginBottom": 0,
        "marginLeft": 0,
        "paddingTop": 0,
        "paddingRight": 0,
        "paddingBottom": 0,
        "paddingLeft": 0,
        "border": 0,
        "fontSize": "100%",
        "font": "inherit",
        "verticalAlign": "baseline"
    },
    "dd": {
        "marginTop": 0,
        "marginRight": 0,
        "marginBottom": 0,
        "marginLeft": 0,
        "paddingTop": 0,
        "paddingRight": 0,
        "paddingBottom": 0,
        "paddingLeft": 0,
        "border": 0,
        "fontSize": "100%",
        "font": "inherit",
        "verticalAlign": "baseline"
    },
    "ol": {
        "marginTop": 0,
        "marginRight": 0,
        "marginBottom": 0,
        "marginLeft": 0,
        "paddingTop": 0,
        "paddingRight": 0,
        "paddingBottom": 0,
        "paddingLeft": 0,
        "border": 0,
        "fontSize": "100%",
        "font": "inherit",
        "verticalAlign": "baseline",
        "listStyle": "none"
    },
    "ul": {
        "marginTop": 0,
        "marginRight": 0,
        "marginBottom": 0,
        "marginLeft": 0,
        "paddingTop": 0,
        "paddingRight": 0,
        "paddingBottom": 0,
        "paddingLeft": 0,
        "border": 0,
        "fontSize": "100%",
        "font": "inherit",
        "verticalAlign": "baseline",
        "listStyle": "none"
    },
    "li": {
        "marginTop": 0,
        "marginRight": 0,
        "marginBottom": 0,
        "marginLeft": 0,
        "paddingTop": 0,
        "paddingRight": 0,
        "paddingBottom": 0,
        "paddingLeft": 0,
        "border": 0,
        "fontSize": "100%",
        "font": "inherit",
        "verticalAlign": "baseline"
    },
    "fieldset": {
        "marginTop": 0,
        "marginRight": 0,
        "marginBottom": 0,
        "marginLeft": 0,
        "paddingTop": 0,
        "paddingRight": 0,
        "paddingBottom": 0,
        "paddingLeft": 0,
        "border": 0,
        "fontSize": "100%",
        "font": "inherit",
        "verticalAlign": "baseline"
    },
    "form": {
        "marginTop": 0,
        "marginRight": 0,
        "marginBottom": 0,
        "marginLeft": 0,
        "paddingTop": 0,
        "paddingRight": 0,
        "paddingBottom": 0,
        "paddingLeft": 0,
        "border": 0,
        "fontSize": "100%",
        "font": "inherit",
        "verticalAlign": "baseline"
    },
    "label": {
        "marginTop": 0,
        "marginRight": 0,
        "marginBottom": 0,
        "marginLeft": 0,
        "paddingTop": 0,
        "paddingRight": 0,
        "paddingBottom": 0,
        "paddingLeft": 0,
        "border": 0,
        "fontSize": "100%",
        "font": "inherit",
        "verticalAlign": "baseline"
    },
    "legend": {
        "marginTop": 0,
        "marginRight": 0,
        "marginBottom": 0,
        "marginLeft": 0,
        "paddingTop": 0,
        "paddingRight": 0,
        "paddingBottom": 0,
        "paddingLeft": 0,
        "border": 0,
        "fontSize": "100%",
        "font": "inherit",
        "verticalAlign": "baseline"
    },
    "table": {
        "marginTop": 0,
        "marginRight": 0,
        "marginBottom": 0,
        "marginLeft": 0,
        "paddingTop": 0,
        "paddingRight": 0,
        "paddingBottom": 0,
        "paddingLeft": 0,
        "border": 0,
        "fontSize": "100%",
        "font": "inherit",
        "verticalAlign": "baseline",
        "borderCollapse": "collapse",
        "borderSpacing": 0
    },
    "caption": {
        "marginTop": 0,
        "marginRight": 0,
        "marginBottom": 0,
        "marginLeft": 0,
        "paddingTop": 0,
        "paddingRight": 0,
        "paddingBottom": 0,
        "paddingLeft": 0,
        "border": 0,
        "fontSize": "100%",
        "font": "inherit",
        "verticalAlign": "baseline"
    },
    "tbody": {
        "marginTop": 0,
        "marginRight": 0,
        "marginBottom": 0,
        "marginLeft": 0,
        "paddingTop": 0,
        "paddingRight": 0,
        "paddingBottom": 0,
        "paddingLeft": 0,
        "border": 0,
        "fontSize": "100%",
        "font": "inherit",
        "verticalAlign": "baseline"
    },
    "tfoot": {
        "marginTop": 0,
        "marginRight": 0,
        "marginBottom": 0,
        "marginLeft": 0,
        "paddingTop": 0,
        "paddingRight": 0,
        "paddingBottom": 0,
        "paddingLeft": 0,
        "border": 0,
        "fontSize": "100%",
        "font": "inherit",
        "verticalAlign": "baseline"
    },
    "thead": {
        "marginTop": 0,
        "marginRight": 0,
        "marginBottom": 0,
        "marginLeft": 0,
        "paddingTop": 0,
        "paddingRight": 0,
        "paddingBottom": 0,
        "paddingLeft": 0,
        "border": 0,
        "fontSize": "100%",
        "font": "inherit",
        "verticalAlign": "baseline"
    },
    "tr": {
        "marginTop": 0,
        "marginRight": 0,
        "marginBottom": 0,
        "marginLeft": 0,
        "paddingTop": 0,
        "paddingRight": 0,
        "paddingBottom": 0,
        "paddingLeft": 0,
        "border": 0,
        "fontSize": "100%",
        "font": "inherit",
        "verticalAlign": "baseline"
    },
    "th": {
        "marginTop": 0,
        "marginRight": 0,
        "marginBottom": 0,
        "marginLeft": 0,
        "paddingTop": 0,
        "paddingRight": 0,
        "paddingBottom": 0,
        "paddingLeft": 0,
        "border": 0,
        "fontSize": "100%",
        "font": "inherit",
        "verticalAlign": "baseline"
    },
    "td": {
        "marginTop": 0,
        "marginRight": 0,
        "marginBottom": 0,
        "marginLeft": 0,
        "paddingTop": 0,
        "paddingRight": 0,
        "paddingBottom": 0,
        "paddingLeft": 0,
        "border": 0,
        "fontSize": "100%",
        "font": "inherit",
        "verticalAlign": "baseline"
    },
    "article": {
        "marginTop": 0,
        "marginRight": 0,
        "marginBottom": 0,
        "marginLeft": 0,
        "paddingTop": 0,
        "paddingRight": 0,
        "paddingBottom": 0,
        "paddingLeft": 0,
        "border": 0,
        "fontSize": "100%",
        "font": "inherit",
        "verticalAlign": "baseline",
        "display": "block"
    },
    "aside": {
        "marginTop": 0,
        "marginRight": 0,
        "marginBottom": 0,
        "marginLeft": 0,
        "paddingTop": 0,
        "paddingRight": 0,
        "paddingBottom": 0,
        "paddingLeft": 0,
        "border": 0,
        "fontSize": "100%",
        "font": "inherit",
        "verticalAlign": "baseline",
        "display": "block"
    },
    "canvas": {
        "marginTop": 0,
        "marginRight": 0,
        "marginBottom": 0,
        "marginLeft": 0,
        "paddingTop": 0,
        "paddingRight": 0,
        "paddingBottom": 0,
        "paddingLeft": 0,
        "border": 0,
        "fontSize": "100%",
        "font": "inherit",
        "verticalAlign": "baseline"
    },
    "details": {
        "marginTop": 0,
        "marginRight": 0,
        "marginBottom": 0,
        "marginLeft": 0,
        "paddingTop": 0,
        "paddingRight": 0,
        "paddingBottom": 0,
        "paddingLeft": 0,
        "border": 0,
        "fontSize": "100%",
        "font": "inherit",
        "verticalAlign": "baseline",
        "display": "block"
    },
    "embed": {
        "marginTop": 0,
        "marginRight": 0,
        "marginBottom": 0,
        "marginLeft": 0,
        "paddingTop": 0,
        "paddingRight": 0,
        "paddingBottom": 0,
        "paddingLeft": 0,
        "border": 0,
        "fontSize": "100%",
        "font": "inherit",
        "verticalAlign": "baseline"
    },
    "figure": {
        "marginTop": 0,
        "marginRight": 0,
        "marginBottom": 0,
        "marginLeft": 0,
        "paddingTop": 0,
        "paddingRight": 0,
        "paddingBottom": 0,
        "paddingLeft": 0,
        "border": 0,
        "fontSize": "100%",
        "font": "inherit",
        "verticalAlign": "baseline",
        "display": "block"
    },
    "figcaption": {
        "marginTop": 0,
        "marginRight": 0,
        "marginBottom": 0,
        "marginLeft": 0,
        "paddingTop": 0,
        "paddingRight": 0,
        "paddingBottom": 0,
        "paddingLeft": 0,
        "border": 0,
        "fontSize": "100%",
        "font": "inherit",
        "verticalAlign": "baseline",
        "display": "block"
    },
    "footer": {
        "marginTop": 0,
        "marginRight": 0,
        "marginBottom": 0,
        "marginLeft": 0,
        "paddingTop": 0,
        "paddingRight": 0,
        "paddingBottom": 0,
        "paddingLeft": 0,
        "border": 0,
        "fontSize": "100%",
        "font": "inherit",
        "verticalAlign": "baseline",
        "display": "block"
    },
    "header": {
        "marginTop": 0,
        "marginRight": 0,
        "marginBottom": 0,
        "marginLeft": 0,
        "paddingTop": 0,
        "paddingRight": 0,
        "paddingBottom": 0,
        "paddingLeft": 0,
        "border": 0,
        "fontSize": "100%",
        "font": "inherit",
        "verticalAlign": "baseline",
        "display": "block"
    },
    "hgroup": {
        "marginTop": 0,
        "marginRight": 0,
        "marginBottom": 0,
        "marginLeft": 0,
        "paddingTop": 0,
        "paddingRight": 0,
        "paddingBottom": 0,
        "paddingLeft": 0,
        "border": 0,
        "fontSize": "100%",
        "font": "inherit",
        "verticalAlign": "baseline",
        "display": "block"
    },
    "menu": {
        "marginTop": 0,
        "marginRight": 0,
        "marginBottom": 0,
        "marginLeft": 0,
        "paddingTop": 0,
        "paddingRight": 0,
        "paddingBottom": 0,
        "paddingLeft": 0,
        "border": 0,
        "fontSize": "100%",
        "font": "inherit",
        "verticalAlign": "baseline",
        "display": "block"
    },
    "nav": {
        "marginTop": 0,
        "marginRight": 0,
        "marginBottom": 0,
        "marginLeft": 0,
        "paddingTop": 0,
        "paddingRight": 0,
        "paddingBottom": 0,
        "paddingLeft": 0,
        "border": 0,
        "fontSize": "100%",
        "font": "inherit",
        "verticalAlign": "baseline",
        "display": "block"
    },
    "output": {
        "marginTop": 0,
        "marginRight": 0,
        "marginBottom": 0,
        "marginLeft": 0,
        "paddingTop": 0,
        "paddingRight": 0,
        "paddingBottom": 0,
        "paddingLeft": 0,
        "border": 0,
        "fontSize": "100%",
        "font": "inherit",
        "verticalAlign": "baseline"
    },
    "ruby": {
        "marginTop": 0,
        "marginRight": 0,
        "marginBottom": 0,
        "marginLeft": 0,
        "paddingTop": 0,
        "paddingRight": 0,
        "paddingBottom": 0,
        "paddingLeft": 0,
        "border": 0,
        "fontSize": "100%",
        "font": "inherit",
        "verticalAlign": "baseline"
    },
    "section": {
        "marginTop": 0,
        "marginRight": 0,
        "marginBottom": 0,
        "marginLeft": 0,
        "paddingTop": 0,
        "paddingRight": 0,
        "paddingBottom": 0,
        "paddingLeft": 0,
        "border": 0,
        "fontSize": "100%",
        "font": "inherit",
        "verticalAlign": "baseline",
        "display": "block"
    },
    "summary": {
        "marginTop": 0,
        "marginRight": 0,
        "marginBottom": 0,
        "marginLeft": 0,
        "paddingTop": 0,
        "paddingRight": 0,
        "paddingBottom": 0,
        "paddingLeft": 0,
        "border": 0,
        "fontSize": "100%",
        "font": "inherit",
        "verticalAlign": "baseline"
    },
    "time": {
        "marginTop": 0,
        "marginRight": 0,
        "marginBottom": 0,
        "marginLeft": 0,
        "paddingTop": 0,
        "paddingRight": 0,
        "paddingBottom": 0,
        "paddingLeft": 0,
        "border": 0,
        "fontSize": "100%",
        "font": "inherit",
        "verticalAlign": "baseline"
    },
    "mark": {
        "marginTop": 0,
        "marginRight": 0,
        "marginBottom": 0,
        "marginLeft": 0,
        "paddingTop": 0,
        "paddingRight": 0,
        "paddingBottom": 0,
        "paddingLeft": 0,
        "border": 0,
        "fontSize": "100%",
        "font": "inherit",
        "verticalAlign": "baseline"
    },
    "audio": {
        "marginTop": 0,
        "marginRight": 0,
        "marginBottom": 0,
        "marginLeft": 0,
        "paddingTop": 0,
        "paddingRight": 0,
        "paddingBottom": 0,
        "paddingLeft": 0,
        "border": 0,
        "fontSize": "100%",
        "font": "inherit",
        "verticalAlign": "baseline"
    },
    "video": {
        "marginTop": 0,
        "marginRight": 0,
        "marginBottom": 0,
        "marginLeft": 0,
        "paddingTop": 0,
        "paddingRight": 0,
        "paddingBottom": 0,
        "paddingLeft": 0,
        "border": 0,
        "fontSize": "100%",
        "font": "inherit",
        "verticalAlign": "baseline"
    },
    "blockquote:before": {
        "content": "none"
    },
    "blockquote:after": {
        "content": "none"
    },
    "q:before": {
        "content": "none"
    },
    "q:after": {
        "content": "none"
    },
    "a:hover": {
        "background": "rgba(255,255,255,1)",
        "textShadow": "-1px -1px 2px rgba(100,100,100,0.5)"
    },
    "a:focus": {
        "background": "rgba(255,255,255,1)",
        "textShadow": "-1px -1px 2px rgba(100,100,100,0.5)"
    },
    "fallback-message": {
        "fontFamily": "sans-serif",
        "lineHeight": 1.3,
        "width": 780,
        "paddingTop": 10,
        "paddingRight": 10,
        "paddingBottom": 0,
        "paddingLeft": 10,
        "marginTop": 20,
        "marginRight": "auto",
        "marginBottom": 20,
        "marginLeft": "auto",
        "border": "1px solid #E4C652",
        "borderRadius": 10,
        "background": "#EEDC94"
    },
    "fallback-message p": {
        "marginBottom": 10
    },
    "impress-supported fallback-message": {
        "display": "none"
    },
    "step": {
        "position": "relative",
        "width": 900,
        "paddingTop": 40,
        "paddingRight": 40,
        "paddingBottom": 40,
        "paddingLeft": 40,
        "marginTop": 20,
        "marginRight": "auto",
        "marginBottom": 20,
        "marginLeft": "auto",
        "WebkitBoxSizing": "border-box",
        "MozBoxSizing": "border-box",
        "MsBoxSizing": "border-box",
        "OBoxSizing": "border-box",
        "boxSizing": "border-box",
        "fontFamily": "'PT Serif', georgia, serif",
        "fontSize": 48,
        "lineHeight": 1.5
    },
    "impress-enabled step": {
        "marginTop": 0,
        "marginRight": 0,
        "marginBottom": 0,
        "marginLeft": 0,
        "opacity": 0.3,
        "WebkitTransition": "opacity 1s",
        "MozTransition": "opacity 1s",
        "MsTransition": "opacity 1s",
        "OTransition": "opacity 1s",
        "transition": "opacity 1s"
    },
    "impress-enabled stepactive": {
        "opacity": 1
    },
    "slide": {
        "display": "block",
        "width": 900,
        "height": 700,
        "paddingTop": 40,
        "paddingRight": 60,
        "paddingBottom": 40,
        "paddingLeft": 60,
        "backgroundColor": "white",
        "border": "1px solid rgba(0, 0, 0, .3)",
        "borderRadius": 10,
        "boxShadow": "0 2px 6px rgba(0, 0, 0, .1)",
        "color": "rgb(102, 102, 102)",
        "textShadow": "0 2px 2px rgba(0, 0, 0, .1)",
        "fontFamily": "'Open Sans', Arial, sans-serif",
        "fontSize": 30,
        "lineHeight": 36,
        "letterSpacing": -1
    },
    "slide q": {
        "display": "block",
        "fontSize": 50,
        "lineHeight": 72,
        "marginTop": 100
    },
    "slide q strong": {
        "whiteSpace": "nowrap"
    },
    "title": {
        "paddingTop": 0,
        "paddingRight": 0,
        "paddingBottom": 0,
        "paddingLeft": 0
    },
    "title try": {
        "fontSize": 64,
        "position": "absolute",
        "top": -0.5,
        "left": 1.5,
        "WebkitTransform": "translateZ(20px)",
        "MozTransform": "translateZ(20px)",
        "MsTransform": "translateZ(20px)",
        "OTransform": "translateZ(20px)",
        "transform": "translateZ(20px)"
    },
    "title h1": {
        "fontSize": 190,
        "WebkitTransform": "translateZ(50px)",
        "MozTransform": "translateZ(50px)",
        "MsTransform": "translateZ(50px)",
        "OTransform": "translateZ(50px)",
        "transform": "translateZ(50px)"
    },
    "title footnote": {
        "fontSize": 32
    },
    "welcome": {
        "width": 600,
        "textAlign": "center",
        "fontSize": 40,
        "lineHeight": 1
    },
    "welcome title": {
        "fontSize": 90,
        "lineHeight": 150
    },
    "welcome footnote": {
        "fontSize": 20
    },
    "tiny": {
        "width": 500,
        "textAlign": "center"
    },
    "me": {
        "width": 600
    },
    "me b": {
        "display": "inline-block",
        "WebkitTransition": "0.5s",
        "MozTransition": "0.5s",
        "MsTransition": "0.5s",
        "OTransition": "0.5s",
        "transition": "0.5s"
    },
    "mepresent now_me": {
        "fontSize": 90,
        "WebkitTransform": "translateY(-10px)",
        "MozTransform": "translateY(-10px)",
        "MsTransform": "translateY(-10px)",
        "OTransform": "translateY(-10px)",
        "transform": "translateY(-10px)"
    },
    "mepresent unity": {
        "WebkitTransform": "translateY(10px)",
        "MozTransform": "translateY(10px)",
        "MsTransform": "translateY(10px)",
        "OTransform": "translateY(10px)",
        "transform": "translateY(10px)",
        "WebkitTransitionDelay": "0.25s",
        "MozTransitionDelay": "0.25s",
        "MsTransitionDelay": "0.25s",
        "OTransitionDelay": "0.25s",
        "transitionDelay": "0.25s"
    },
    "mepresent ios": {
        "WebkitTransform": "translateY(10px)",
        "MozTransform": "translateY(10px)",
        "MsTransform": "translateY(10px)",
        "OTransform": "translateY(10px)",
        "transform": "translateY(10px)",
        "WebkitTransitionDelay": "0.5s",
        "MozTransitionDelay": "0.5s",
        "MsTransitionDelay": "0.5s",
        "OTransitionDelay": "0.5s",
        "transitionDelay": "0.5s"
    },
    "mepresent photo": {
        "WebkitTransform": "translateY(10px)",
        "MozTransform": "translateY(10px)",
        "MsTransform": "translateY(10px)",
        "OTransform": "translateY(10px)",
        "transform": "translateY(10px)",
        "WebkitTransitionDelay": "0.75s",
        "MozTransitionDelay": "0.75s",
        "MsTransitionDelay": "0.75s",
        "OTransitionDelay": "0.75s",
        "transitionDelay": "0.75s"
    },
    "whereiam": {
        "width": 600
    },
    "whereiam born": {
        "textAlign": "right",
        "fontSize": 30
    },
    "whereiam study": {
        "textAlign": "right",
        "fontSize": 30
    },
    "whereiam kunming": {
        "color": "green"
    },
    "whereiam keyboard": {
        "color": "purple"
    },
    "location": {
        "width": 650
    },
    "location b": {
        "display": "inline-block",
        "WebkitTransition": "0.5s",
        "MozTransition": "0.5s",
        "MsTransition": "0.5s",
        "OTransition": "0.5s",
        "transition": "0.5s"
    },
    "locationpresent trans": {
        "WebkitTransform": "translateX(100px)",
        "MozTransform": "translateX(100px)",
        "MsTransform": "translateX(100px)",
        "OTransform": "translateX(100px)",
        "transform": "translateX(100px)",
        "WebkitTransitionDelay": "0.5s",
        "MozTransitionDelay": "0.5s",
        "MsTransitionDelay": "0.5s",
        "OTransitionDelay": "0.5s",
        "transitionDelay": "0.5s"
    },
    "location footnote": {
        "fontSize": 15
    },
    "meet": {
        "textAlign": "center"
    },
    "comein": {
        "width": 1000,
        "textAlign": "center"
    },
    "mywords": {
        "width": 1000,
        "textAlign": "center"
    },
    "grow": {
        "textAlign": "center"
    },
    "knowme": {
        "fontSize": 45
    },
    "imagination": {
        "width": 600
    },
    "imagination imagination": {
        "fontSize": 78
    },
    "findme": {
        "width": 900,
        "paddingBottom": 150,
        "backgroundImage": "url(https://dn-coding-net-production-static.qbox.me/91d0106b-7774-4878-b72e-304fcf2059af.png?imageMogr2/auto-orient/format/png/crop/!300x220a19a0)",
        "backgroundPosition": "bottom right",
        "backgroundRepeat": "no-repeat"
    },
    "findme adv": {
        "fontSize": 31,
        "fontStyle": "oblique",
        "color": "orange",
        "marginBottom": 10
    },
    "prizeme p": {
        "WebkitTransformStyle": "preserve-3d",
        "MozTransformStyle": "preserve-3d",
        "MsTransformStyle": "preserve-3d",
        "OTransformStyle": "preserve-3d",
        "transformStyle": "preserve-3d"
    },
    "prizeme span": {
        "display": "inline-block",
        "WebkitTransform": "translateZ(40px)",
        "MozTransform": "translateZ(40px)",
        "MsTransform": "translateZ(40px)",
        "OTransform": "translateZ(40px)",
        "transform": "translateZ(40px)",
        "WebkitTransition": "0.5s",
        "MozTransition": "0.5s",
        "MsTransition": "0.5s",
        "OTransition": "0.5s",
        "transition": "0.5s"
    },
    "prizeme b": {
        "display": "inline-block",
        "WebkitTransform": "translateZ(40px)",
        "MozTransform": "translateZ(40px)",
        "MsTransform": "translateZ(40px)",
        "OTransform": "translateZ(40px)",
        "transform": "translateZ(40px)",
        "WebkitTransition": "0.5s",
        "MozTransition": "0.5s",
        "MsTransition": "0.5s",
        "OTransition": "0.5s",
        "transition": "0.5s"
    },
    "prizeme horse": {
        "WebkitTransform": "translateZ(-40px)",
        "MozTransform": "translateZ(-40px)",
        "MsTransform": "translateZ(-40px)",
        "OTransform": "translateZ(-40px)",
        "transform": "translateZ(-40px)"
    },
    "prizeme moutain": {
        "WebkitTransform": "translateZ(20px)",
        "MozTransform": "translateZ(20px)",
        "MsTransform": "translateZ(20px)",
        "OTransform": "translateZ(20px)",
        "transform": "translateZ(20px)"
    },
    "prizeme hope": {
        "WebkitTransform": "translateZ(-40px)",
        "MozTransform": "translateZ(-40px)",
        "MsTransform": "translateZ(-40px)",
        "OTransform": "translateZ(-40px)",
        "transform": "translateZ(-40px)"
    },
    "prizeme youare": {
        "WebkitTransform": "translateZ(60px)",
        "MozTransform": "translateZ(60px)",
        "MsTransform": "translateZ(60px)",
        "OTransform": "translateZ(60px)",
        "transform": "translateZ(60px)"
    },
    "prizeme my": {
        "WebkitTransform": "translateZ(-10px)",
        "MozTransform": "translateZ(-10px)",
        "MsTransform": "translateZ(-10px)",
        "OTransform": "translateZ(-10px)",
        "transform": "translateZ(-10px)"
    },
    "prizemepresent span": {
        "WebkitTransform": "translateZ(0px)",
        "MozTransform": "translateZ(0px)",
        "MsTransform": "translateZ(0px)",
        "OTransform": "translateZ(0px)",
        "transform": "translateZ(0px)"
    },
    "prizemepresent b": {
        "WebkitTransform": "translateZ(0px)",
        "MozTransform": "translateZ(0px)",
        "MsTransform": "translateZ(0px)",
        "OTransform": "translateZ(0px)",
        "transform": "translateZ(0px)"
    },
    "subcribe adv": {
        "fontSize": 30,
        "fontStyle": "oblique",
        "color": "green",
        "marginTop": 10
    },
    "motto": {
        "textAlign": "center"
    },
    "motto b": {
        "fontSize": 70,
        "color": "darkred",
        "fontWeight": "bold"
    },
    "back": {
        "width": 700,
        "paddingBottom": 400,
        "backgroundImage": "url(https://avatars1.githubusercontent.com/u/4197468?v=3&s=400)",
        "backgroundPosition": "bottom right",
        "backgroundRepeat": "no-repeat"
    },
    "overview": {
        "display": "none"
    },
    "impress-on-overview step": {
        "opacity": 1,
        "cursor": "pointer"
    },
    "hint": {
        "display": "none",
        "position": "fixed",
        "left": 0,
        "right": 0,
        "bottom": 0,
        "background": "rgba(0,0,0,0.5)",
        "color": "#EEE",
        "textAlign": "center",
        "fontSize": 50,
        "paddingTop": 20,
        "paddingRight": 20,
        "paddingBottom": 20,
        "paddingLeft": 20,
        "zIndex": 100,
        "opacity": 0,
        "WebkitTransform": "translateY(400px)",
        "MozTransform": "translateY(400px)",
        "MsTransform": "translateY(400px)",
        "OTransform": "translateY(400px)",
        "transform": "translateY(400px)",
        "WebkitTransition": "opacity 1s, -webkit-transform 0.5s 1s",
        "MozTransition": "opacity 1s,    -moz-transform 0.5s 1s",
        "MsTransition": "opacity 1s,     -ms-transform 0.5s 1s",
        "OTransition": "opacity 1s,      -o-transform 0.5s 1s",
        "transition": "opacity 1s,         transform 0.5s 1s"
    },
    "impress-enabled hint": {
        "display": "block"
    },
    "impress-on-welcome hint": {
        "opacity": 1,
        "WebkitTransform": "translateY(0px)",
        "MozTransform": "translateY(0px)",
        "MsTransform": "translateY(0px)",
        "OTransform": "translateY(0px)",
        "transform": "translateY(0px)",
        "WebkitTransition": "opacity 1s 3s, -webkit-transform 0.5s 2.5s",
        "MozTransition": "opacity 1s 3s,    -moz-transform 0.5s 2.5s",
        "MsTransition": "opacity 1s 3s,     -ms-transform 0.5s 2.5s",
        "OTransition": "opacity 1s 3s,      -o-transform 0.5s 2.5s",
        "transition": "opacity 1s 3s,         transform 0.5s 2.5s"
    },
    "impress-enabled": {
        "pointerEvents": "none"
    },
    "impress-enabled impress": {
        "pointerEvents": "auto"
    }
});